[package]
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license-file.workspace = true
name = "libp2p-length-prefix-codec"
repository.workspace = true
version = "0.1.0"

[dependencies]
async-trait = { workspace = true }

# NOTE(@jmg-duarte,12/03/2025): we're using cbor4ii instead of cborium to match libp2p!
# Or maybe we could replace the cborium usage with cbor4ii:
# https://github.com/quininer/cbor4ii/issues/3#issuecomment-2326382276
cbor4ii = { workspace = true, features = ["serde1", "use_std"] }
futures = { workspace = true }
libp2p = { workspace = true, features = ["request-response"] }
serde = { workspace = true, features = ["derive"] }
unsigned-varint = { workspace = true }


[lints]
workspace = true
