[package]
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license-file.workspace = true
name = "primitives"
repository.workspace = true
version = "0.1.0"

[dependencies]
cid = { workspace = true, default-features = false, features = ["alloc"] }
clap = { workspace = true, features = ["derive"], optional = true }
codec = { workspace = true, features = ["derive"] }
ed25519-dalek = { workspace = true, optional = true, features = ["pem"] }
filecoin-proofs = { workspace = true, optional = true }
hex = { workspace = true, optional = true }
scale-decode = { workspace = true, features = ["derive"] }
scale-encode = { workspace = true, features = ["derive"] }
scale-info = { workspace = true, features = ["derive"] }
sealed = { workspace = true }
serde = { workspace = true, optional = true, features = ["derive"] }
sha2 = { workspace = true }
sp-api = { workspace = true }
sp-core = { workspace = true }
sp-io = { workspace = true, default-features = false }
sp-runtime = { workspace = true }
sp-std = { workspace = true }
thiserror = { workspace = true }
frame-support = { workspace = true, default-features = false }
frame-system = { workspace = true, default-features = false }

[dev-dependencies]
rand = { workspace = true, default-features = true }
serde_json = { workspace = true, default-features = true }

[lints]
workspace = true

[features]
builder = []
clap = ["dep:clap", "std"]
default = ["std"]
serde = ["dep:serde"]
std = [
  "cid/scale-codec",
  "cid/serde",
  "cid/std",
  "codec/std",
  "dep:ed25519-dalek",
  "dep:filecoin-proofs",
  "dep:hex",
  "frame-support/std",
  "frame-system/std",
  "scale-info/std",
  "serde/std",
  "sha2/std",
  "sp-api/std",
  "sp-core/std",
  "sp-io/std",
  "sp-runtime/std",
  "sp-std/std",
  "thiserror/std",
]
# This feature provides testing utilities,
# e.g. a dummy proof verifier
testing = []
