
//! Autogenerated weights for `pallet_proofs`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2025-02-17, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `parthenon`, CPU: `12th Gen Intel(R) Core(TM) i7-12700H`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// target/release/polka-storage-node
// benchmark
// pallet
// --wasm-execution=compiled
// --pallet
// pallet_proofs
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --template
// node/benchmark_template.hbs
// --output
// pallets/proofs/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

pub trait WeightInfo {
    fn set_porep_verifying_key() -> Weight;
    fn set_post_verifying_key() -> Weight;
}

/// Weight functions for `pallet_proofs`.
pub struct Weights<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for Weights<T> {
    /// Storage: `Proofs::PoRepVerifyingKeys` (r:0 w:1)
    /// Proof: `Proofs::PoRepVerifyingKeys` (`max_values`: None, `max_size`: Some(4725), added: 7200, mode: `MaxEncodedLen`)
    fn set_porep_verifying_key() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 8_973_058_000 picoseconds.
        Weight::from_parts(9_095_053_000, 0)
            .saturating_add(Weight::from_parts(0, 0))
            .saturating_add(T::DbWeight::get().writes(1))
    }
    /// Storage: `Proofs::PoStVerifyingKeys` (r:0 w:1)
    /// Proof: `Proofs::PoStVerifyingKeys` (`max_values`: None, `max_size`: Some(4725), added: 7200, mode: `MaxEncodedLen`)
    fn set_post_verifying_key() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 9_007_137_000 picoseconds.
        Weight::from_parts(9_101_806_000, 0)
            .saturating_add(Weight::from_parts(0, 0))
            .saturating_add(T::DbWeight::get().writes(1))
    }
}

impl WeightInfo for () {
    /// Storage: `Proofs::PoRepVerifyingKeys` (r:0 w:1)
    /// Proof: `Proofs::PoRepVerifyingKeys` (`max_values`: None, `max_size`: Some(4725), added: 7200, mode: `MaxEncodedLen`)
    fn set_porep_verifying_key() -> Weight {
        use frame_support::weights::constants::RocksDbWeight;

        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 8_973_058_000 picoseconds.
        Weight::from_parts(9_095_053_000, 0)
            .saturating_add(Weight::from_parts(0, 0))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    /// Storage: `Proofs::PoStVerifyingKeys` (r:0 w:1)
    /// Proof: `Proofs::PoStVerifyingKeys` (`max_values`: None, `max_size`: Some(4725), added: 7200, mode: `MaxEncodedLen`)
    fn set_post_verifying_key() -> Weight {
        use frame_support::weights::constants::RocksDbWeight;

        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 9_007_137_000 picoseconds.
        Weight::from_parts(9_101_806_000, 0)
            .saturating_add(Weight::from_parts(0, 0))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
}
