[package]
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license-file.workspace = true
name = "polka-storage-provider-server"
repository.workspace = true
version = "0.1.0"

[features]
cuda = ["polka-storage-proofs/cuda", "polka-storage-proofs/std", "polka-storage-proofs/substrate"]
default = ["opencl"]
opencl = ["polka-storage-proofs/opencl", "polka-storage-proofs/std", "polka-storage-proofs/substrate"]

[dependencies]
# "Homegrown" crates
mater = { workspace = true }
polka-storage-proofs = { workspace = true, default-features = false }
polka-storage-provider-common = { workspace = true, features = ["clap"] }
primitives = { workspace = true, features = ["clap", "serde", "std"] }
primitives-p2p = { workspace = true, features = ["serde"] }
storagext = { workspace = true, features = ["clap"] }

async-trait = { workspace = true }
axum = { workspace = true, features = ["macros", "multipart"] }
base64 = { workspace = true }
beetswap = { workspace = true }
blockstore = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
ciborium = { workspace = true }
cid = { workspace = true, features = ["serde", "std"] }
clap = { workspace = true, features = ["derive"] }
futures = { workspace = true }
hyper = { workspace = true }
integer-encoding = { workspace = true }
jsonrpsee = { workspace = true, features = ["http-client", "macros", "server", "ws-client"] }
libp2p = { workspace = true, features = ["cbor", "dns", "identify", "macros", "noise", "request-response", "tcp", "tokio", "websocket", "yamux"] }
libp2p-length-prefix-codec = { workspace = true }
rand = { workspace = true }
rocksdb = { workspace = true }
sc-cli = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
subxt = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "signal", "sync", "time"] }
tokio-util = { workspace = true, features = ["rt"] }
toml = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true, features = ["trace"] }
tracing = { workspace = true }
tracing-appender = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
url = { workspace = true, features = ["serde"] }
uuid = { workspace = true, features = ["serde", "v4"] }

[dev-dependencies]
sha2 = { workspace = true }

[lints]
workspace = true
