[package]
name = "storagext-cli"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license-file.workspace = true
repository.workspace = true

[features]
insecure_url = ["storagext/insecure_url"]

[dependencies]
storagext.workspace = true

anyhow.workspace = true
cid = { workspace = true, features = ["scale-codec"] }
clap = { workspace = true, features = ["derive"] }
codec.workspace = true
frame-support = { workspace = true, features = ["std"] }
hex.workspace = true
primitives-proofs = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
subxt = { workspace = true, features = ["jsonrpsee", "substrate-compat"] }
subxt-signer = { workspace = true, features = ["subxt"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
url = { workspace = true }

[lints]
workspace = true
