
//! Autogenerated weights for `pallet_market`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2025-01-24, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `parthenon`, CPU: `12th Gen Intel(R) Core(TM) i7-12700H`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// target/release/polka-storage-node
// benchmark
// pallet
// --wasm-execution=compiled
// --pallet
// pallet_market
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// pallets/market/src/weights.rs
// --template
// node/benchmark_template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

pub trait WeightInfo {
    fn add_balance() -> Weight;
    fn withdraw_balance() -> Weight;
    fn publish_storage_deals(n: u32, ) -> Weight;
    fn settle_deal_payments(n: u32, ) -> Weight;
}

/// Weight functions for `pallet_market`.
pub struct Weights<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for Weights<T> {
    /// Storage: `Market::BalanceTable` (r:1 w:1)
    /// Proof: `Market::BalanceTable` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `System::Account` (r:1 w:1)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    fn add_balance() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `76`
        //  Estimated: `3593`
        // Minimum execution time: 42_074_000 picoseconds.
        Weight::from_parts(42_849_000, 0)
            .saturating_add(Weight::from_parts(0, 3593))
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(2))
    }
    /// Storage: `Market::BalanceTable` (r:1 w:1)
    /// Proof: `Market::BalanceTable` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `System::Account` (r:1 w:1)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    fn withdraw_balance() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `285`
        //  Estimated: `3750`
        // Minimum execution time: 48_792_000 picoseconds.
        Weight::from_parts(49_733_000, 0)
            .saturating_add(Weight::from_parts(0, 3750))
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(2))
    }
    /// Storage: `StorageProvider::StorageProviders` (r:1 w:0)
    /// Proof: `StorageProvider::StorageProviders` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `Market::BalanceTable` (r:2 w:2)
    /// Proof: `Market::BalanceTable` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `Market::PendingProposals` (r:1 w:1)
    /// Proof: `Market::PendingProposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    /// Storage: `Market::NextDealId` (r:1 w:1)
    /// Proof: `Market::NextDealId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    /// Storage: `Market::DealsForBlock` (r:1 w:1)
    /// Proof: `Market::DealsForBlock` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `Market::Proposals` (r:0 w:128)
    /// Proof: `Market::Proposals` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// The range of component `n` is `[1, 128]`.
    fn publish_storage_deals(n: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `383`
        //  Estimated: `6323`
        // Minimum execution time: 63_315_000 picoseconds.
        Weight::from_parts(65_960_000, 0)
            .saturating_add(Weight::from_parts(0, 6323))
            // Standard Error: 78_356
            .saturating_add(Weight::from_parts(50_851_959, 0).saturating_mul(n.into()))
            .saturating_add(T::DbWeight::get().reads(6))
            .saturating_add(T::DbWeight::get().writes(5))
            .saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(n.into())))
    }
    /// Storage: `Market::Proposals` (r:128 w:128)
    /// Proof: `Market::Proposals` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `Market::BalanceTable` (r:2 w:2)
    /// Proof: `Market::BalanceTable` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// The range of component `n` is `[1, 128]`.
    fn settle_deal_payments(n: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `372 + n * (336 ±0)`
        //  Estimated: `6311 + n * (2812 ±0)`
        // Minimum execution time: 28_818_000 picoseconds.
        Weight::from_parts(28_773_328, 0)
            .saturating_add(Weight::from_parts(0, 6311))
            // Standard Error: 21_440
            .saturating_add(Weight::from_parts(8_383_425, 0).saturating_mul(n.into()))
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
            .saturating_add(T::DbWeight::get().writes(2))
            .saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(n.into())))
            .saturating_add(Weight::from_parts(0, 2812).saturating_mul(n.into()))
    }
}

impl WeightInfo for () {
    /// Storage: `Market::BalanceTable` (r:1 w:1)
    /// Proof: `Market::BalanceTable` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `System::Account` (r:1 w:1)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    fn add_balance() -> Weight {
        use frame_support::weights::constants::RocksDbWeight;

        // Proof Size summary in bytes:
        //  Measured:  `76`
        //  Estimated: `3593`
        // Minimum execution time: 42_074_000 picoseconds.
        Weight::from_parts(42_849_000, 0)
            .saturating_add(Weight::from_parts(0, 3593))
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(2))
    }
    /// Storage: `Market::BalanceTable` (r:1 w:1)
    /// Proof: `Market::BalanceTable` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `System::Account` (r:1 w:1)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    fn withdraw_balance() -> Weight {
        use frame_support::weights::constants::RocksDbWeight;

        // Proof Size summary in bytes:
        //  Measured:  `285`
        //  Estimated: `3750`
        // Minimum execution time: 48_792_000 picoseconds.
        Weight::from_parts(49_733_000, 0)
            .saturating_add(Weight::from_parts(0, 3750))
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(2))
    }
    /// Storage: `StorageProvider::StorageProviders` (r:1 w:0)
    /// Proof: `StorageProvider::StorageProviders` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `Market::BalanceTable` (r:2 w:2)
    /// Proof: `Market::BalanceTable` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `Market::PendingProposals` (r:1 w:1)
    /// Proof: `Market::PendingProposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    /// Storage: `Market::NextDealId` (r:1 w:1)
    /// Proof: `Market::NextDealId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    /// Storage: `Market::DealsForBlock` (r:1 w:1)
    /// Proof: `Market::DealsForBlock` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `Market::Proposals` (r:0 w:128)
    /// Proof: `Market::Proposals` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// The range of component `n` is `[1, 128]`.
    fn publish_storage_deals(n: u32, ) -> Weight {
        use frame_support::weights::constants::RocksDbWeight;

        // Proof Size summary in bytes:
        //  Measured:  `383`
        //  Estimated: `6323`
        // Minimum execution time: 63_315_000 picoseconds.
        Weight::from_parts(65_960_000, 0)
            .saturating_add(Weight::from_parts(0, 6323))
            // Standard Error: 78_356
            .saturating_add(Weight::from_parts(50_851_959, 0).saturating_mul(n.into()))
            .saturating_add(RocksDbWeight::get().reads(6))
            .saturating_add(RocksDbWeight::get().writes(5))
            .saturating_add(RocksDbWeight::get().writes((1_u64).saturating_mul(n.into())))
    }
    /// Storage: `Market::Proposals` (r:128 w:128)
    /// Proof: `Market::Proposals` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `Market::BalanceTable` (r:2 w:2)
    /// Proof: `Market::BalanceTable` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// The range of component `n` is `[1, 128]`.
    fn settle_deal_payments(n: u32, ) -> Weight {
        use frame_support::weights::constants::RocksDbWeight;

        // Proof Size summary in bytes:
        //  Measured:  `372 + n * (336 ±0)`
        //  Estimated: `6311 + n * (2812 ±0)`
        // Minimum execution time: 28_818_000 picoseconds.
        Weight::from_parts(28_773_328, 0)
            .saturating_add(Weight::from_parts(0, 6311))
            // Standard Error: 21_440
            .saturating_add(Weight::from_parts(8_383_425, 0).saturating_mul(n.into()))
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(n.into())))
            .saturating_add(RocksDbWeight::get().writes(2))
            .saturating_add(RocksDbWeight::get().writes((1_u64).saturating_mul(n.into())))
            .saturating_add(Weight::from_parts(0, 2812).saturating_mul(n.into()))
    }
}
