
//! Autogenerated weights for `pallet_market`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2025-02-26, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `skimask`, CPU: `AMD Ryzen 5 1500X Quad-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// target/release/polka-storage-node
// benchmark
// pallet
// --wasm-execution=compiled
// --pallet
// pallet_market
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --template
// node/benchmark_template.hbs
// --output
// pallets/market/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

pub trait WeightInfo {
    fn add_balance() -> Weight;
    fn withdraw_balance() -> Weight;
    fn publish_storage_deals(n: u32, ) -> Weight;
    fn settle_deal_payments(n: u32, ) -> Weight;
    fn publish_deal_parameters() -> Weight;
    fn remove_deal_parameters() -> Weight;
}

/// Weight functions for `pallet_market`.
pub struct Weights<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for Weights<T> {
    /// Storage: `Market::BalanceTable` (r:1 w:1)
    /// Proof: `Market::BalanceTable` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `System::Account` (r:1 w:1)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    fn add_balance() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `76`
        //  Estimated: `3593`
        // Minimum execution time: 75_560_000 picoseconds.
        Weight::from_parts(76_452_000, 0)
            .saturating_add(Weight::from_parts(0, 3593))
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(2))
    }
    /// Storage: `Market::BalanceTable` (r:1 w:1)
    /// Proof: `Market::BalanceTable` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `System::Account` (r:1 w:1)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    fn withdraw_balance() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `285`
        //  Estimated: `3750`
        // Minimum execution time: 86_380_000 picoseconds.
        Weight::from_parts(93_493_000, 0)
            .saturating_add(Weight::from_parts(0, 3750))
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(2))
    }
    /// Storage: `StorageProvider::StorageProviders` (r:1 w:0)
    /// Proof: `StorageProvider::StorageProviders` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `Market::SPDealParameters` (r:1 w:0)
    /// Proof: `Market::SPDealParameters` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `Market::BalanceTable` (r:2 w:2)
    /// Proof: `Market::BalanceTable` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `Market::PendingProposals` (r:1 w:1)
    /// Proof: `Market::PendingProposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    /// Storage: `Market::NextDealId` (r:1 w:1)
    /// Proof: `Market::NextDealId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    /// Storage: `Market::DealsForBlock` (r:1 w:1)
    /// Proof: `Market::DealsForBlock` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `Market::Proposals` (r:0 w:128)
    /// Proof: `Market::Proposals` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// The range of component `n` is `[1, 128]`.
    fn publish_storage_deals(n: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `383`
        //  Estimated: `6323`
        // Minimum execution time: 136_233_000 picoseconds.
        Weight::from_parts(136_683_000, 0)
            .saturating_add(Weight::from_parts(0, 6323))
            // Standard Error: 210_780
            .saturating_add(Weight::from_parts(111_856_904, 0).saturating_mul(n.into()))
            .saturating_add(T::DbWeight::get().reads(7))
            .saturating_add(T::DbWeight::get().writes(5))
            .saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(n.into())))
    }
    /// Storage: `Market::Proposals` (r:128 w:128)
    /// Proof: `Market::Proposals` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `Market::BalanceTable` (r:2 w:2)
    /// Proof: `Market::BalanceTable` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// The range of component `n` is `[1, 128]`.
    fn settle_deal_payments(n: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `372 + n * (336 ±0)`
        //  Estimated: `6311 + n * (2812 ±0)`
        // Minimum execution time: 52_487_000 picoseconds.
        Weight::from_parts(18_096_098, 0)
            .saturating_add(Weight::from_parts(0, 6311))
            // Standard Error: 51_318
            .saturating_add(Weight::from_parts(18_909_875, 0).saturating_mul(n.into()))
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
            .saturating_add(T::DbWeight::get().writes(2))
            .saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(n.into())))
            .saturating_add(Weight::from_parts(0, 2812).saturating_mul(n.into()))
    }
    /// Storage: `StorageProvider::StorageProviders` (r:1 w:0)
    /// Proof: `StorageProvider::StorageProviders` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `Market::SPDealParameters` (r:1 w:1)
    /// Proof: `Market::SPDealParameters` (`max_values`: None, `max_size`: None, mode: `Measured`)
    fn publish_deal_parameters() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `186`
        //  Estimated: `3651`
        // Minimum execution time: 24_796_000 picoseconds.
        Weight::from_parts(26_850_000, 0)
            .saturating_add(Weight::from_parts(0, 3651))
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }
    /// Storage: `StorageProvider::StorageProviders` (r:1 w:0)
    /// Proof: `StorageProvider::StorageProviders` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `Market::SPDealParameters` (r:0 w:1)
    /// Proof: `Market::SPDealParameters` (`max_values`: None, `max_size`: None, mode: `Measured`)
    fn remove_deal_parameters() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `110`
        //  Estimated: `3575`
        // Minimum execution time: 20_929_000 picoseconds.
        Weight::from_parts(21_439_000, 0)
            .saturating_add(Weight::from_parts(0, 3575))
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }
}

impl WeightInfo for () {
    /// Storage: `Market::BalanceTable` (r:1 w:1)
    /// Proof: `Market::BalanceTable` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `System::Account` (r:1 w:1)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    fn add_balance() -> Weight {
        use frame_support::weights::constants::RocksDbWeight;

        // Proof Size summary in bytes:
        //  Measured:  `76`
        //  Estimated: `3593`
        // Minimum execution time: 75_560_000 picoseconds.
        Weight::from_parts(76_452_000, 0)
            .saturating_add(Weight::from_parts(0, 3593))
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(2))
    }
    /// Storage: `Market::BalanceTable` (r:1 w:1)
    /// Proof: `Market::BalanceTable` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `System::Account` (r:1 w:1)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    fn withdraw_balance() -> Weight {
        use frame_support::weights::constants::RocksDbWeight;

        // Proof Size summary in bytes:
        //  Measured:  `285`
        //  Estimated: `3750`
        // Minimum execution time: 86_380_000 picoseconds.
        Weight::from_parts(93_493_000, 0)
            .saturating_add(Weight::from_parts(0, 3750))
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(2))
    }
    /// Storage: `StorageProvider::StorageProviders` (r:1 w:0)
    /// Proof: `StorageProvider::StorageProviders` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `Market::SPDealParameters` (r:1 w:0)
    /// Proof: `Market::SPDealParameters` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `Market::BalanceTable` (r:2 w:2)
    /// Proof: `Market::BalanceTable` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `Market::PendingProposals` (r:1 w:1)
    /// Proof: `Market::PendingProposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    /// Storage: `Market::NextDealId` (r:1 w:1)
    /// Proof: `Market::NextDealId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    /// Storage: `Market::DealsForBlock` (r:1 w:1)
    /// Proof: `Market::DealsForBlock` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `Market::Proposals` (r:0 w:128)
    /// Proof: `Market::Proposals` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// The range of component `n` is `[1, 128]`.
    fn publish_storage_deals(n: u32, ) -> Weight {
        use frame_support::weights::constants::RocksDbWeight;

        // Proof Size summary in bytes:
        //  Measured:  `383`
        //  Estimated: `6323`
        // Minimum execution time: 136_233_000 picoseconds.
        Weight::from_parts(136_683_000, 0)
            .saturating_add(Weight::from_parts(0, 6323))
            // Standard Error: 210_780
            .saturating_add(Weight::from_parts(111_856_904, 0).saturating_mul(n.into()))
            .saturating_add(RocksDbWeight::get().reads(7))
            .saturating_add(RocksDbWeight::get().writes(5))
            .saturating_add(RocksDbWeight::get().writes((1_u64).saturating_mul(n.into())))
    }
    /// Storage: `Market::Proposals` (r:128 w:128)
    /// Proof: `Market::Proposals` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `Market::BalanceTable` (r:2 w:2)
    /// Proof: `Market::BalanceTable` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// The range of component `n` is `[1, 128]`.
    fn settle_deal_payments(n: u32, ) -> Weight {
        use frame_support::weights::constants::RocksDbWeight;

        // Proof Size summary in bytes:
        //  Measured:  `372 + n * (336 ±0)`
        //  Estimated: `6311 + n * (2812 ±0)`
        // Minimum execution time: 52_487_000 picoseconds.
        Weight::from_parts(18_096_098, 0)
            .saturating_add(Weight::from_parts(0, 6311))
            // Standard Error: 51_318
            .saturating_add(Weight::from_parts(18_909_875, 0).saturating_mul(n.into()))
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(n.into())))
            .saturating_add(RocksDbWeight::get().writes(2))
            .saturating_add(RocksDbWeight::get().writes((1_u64).saturating_mul(n.into())))
            .saturating_add(Weight::from_parts(0, 2812).saturating_mul(n.into()))
    }
    /// Storage: `StorageProvider::StorageProviders` (r:1 w:0)
    /// Proof: `StorageProvider::StorageProviders` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `Market::SPDealParameters` (r:1 w:1)
    /// Proof: `Market::SPDealParameters` (`max_values`: None, `max_size`: None, mode: `Measured`)
    fn publish_deal_parameters() -> Weight {
        use frame_support::weights::constants::RocksDbWeight;

        // Proof Size summary in bytes:
        //  Measured:  `186`
        //  Estimated: `3651`
        // Minimum execution time: 24_796_000 picoseconds.
        Weight::from_parts(26_850_000, 0)
            .saturating_add(Weight::from_parts(0, 3651))
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    /// Storage: `StorageProvider::StorageProviders` (r:1 w:0)
    /// Proof: `StorageProvider::StorageProviders` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `Market::SPDealParameters` (r:0 w:1)
    /// Proof: `Market::SPDealParameters` (`max_values`: None, `max_size`: None, mode: `Measured`)
    fn remove_deal_parameters() -> Weight {
        use frame_support::weights::constants::RocksDbWeight;

        // Proof Size summary in bytes:
        //  Measured:  `110`
        //  Estimated: `3575`
        // Minimum execution time: 20_929_000 picoseconds.
        Weight::from_parts(21_439_000, 0)
            .saturating_add(Weight::from_parts(0, 3575))
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
}
