[package]
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license-file.workspace = true
name = "primitives-benchmarks"
repository.workspace = true
version = "0.1.0"

[dependencies]
primitives = { workspace = true, default-features = false }

codec = { workspace = true, features = ["derive"] }
sp-core = { workspace = true }
sp-io = { workspace = true, default-features = false }
sp-runtime = { workspace = true }

# Frame deps
frame-benchmarking = { workspace = true, default-features = false }
frame-support = { workspace = true, default-features = false }
frame-system = { workspace = true, default-features = false }


[lints]
workspace = true

[features]
builder = []
default = ["std"]
std = ["codec/std", "frame-benchmarking/std", "frame-support/std", "frame-system/std", "primitives/std", "sp-core/std", "sp-io/std", "sp-runtime/std"]
