[relaychain]
chain = "rococo-local"
default_args = ["--detailed-log-output", "-lparachain=debug,xcm=trace,runtime=trace"]
default_command = "polkadot"

[[relaychain.nodes]]
name = "alice"
validator = true

[[relaychain.nodes]]
name = "bob"
validator = true

[[parachains]]
chain_spec_path = "./chain_spec.json"
id = 1000

[parachains.collator]
args = [
  "--detailed-log-output",
  "--pool-type=fork-aware",
  "-lparachain=debug,xcm=trace,runtime=trace,txpool=debug,basic-authorship=debug,polka_storage_node::service::p2p=trace,libp2p=debug",
]
command = "polkadot-omni-node"
name = "charlie"
rpc_port = 42069
