[relaychain]
chain = "rococo-local"
# That's because in Nix supplied `polkadot` binary, `SKIP_WASM_BUILD=1` is disabled.
# https://github.com/andresilva/polkadot.nix/blob/ac4e91a0c75cf422b80f06d6edcecb9bf63727e3/pkgs/polkadot-sdk/generic.nix#L84
# Needed to generate chainspec by directly downloading polkadot binary (https://github.com/paritytech/polkadot-sdk/releases/download/polkadot-stable2412-1/polkadot)
# and running /polkadot build-spec --chain rococo-local > rococo-local.json`.
# We won't need to add `chain_spec_path` when https://github.com/paritytech/polkadot-sdk/pull/7008 is merged.
chain_spec_path = "./zombienet/rococo-local.json"
default_args = ["--detailed-log-output", "-lparachain=debug,xcm=trace,runtime=trace"]
default_command = "polkadot"

[[relaychain.nodes]]
name = "erin"
validator = true

[[parachains]]
cumulus_based = true

# We need to use a Parachain of an existing System Chain (https://github.com/paritytech/polkadot-sdk/blob/master/polkadot/runtime/rococo/src/xcm_config.rs).
# The reason: being able to get native DOTs from Relay Chain to Parachain via XCM Teleport.
# We'll have a proper Parachain ID in the *future*, but for now, let's stick to 1000 (which is AssetHub and trusted).
id = 1000

# run david as parachain collator
[[parachains.collators]]
args = [
  "--bootstrap-addresses=/ip4/127.0.0.1/tcp/62649",
  "--detailed-log-output",
  "--p2p-key=@/tmp/zombienet/david-private.pem",
  "--p2p-listen-address=/ip4/127.0.0.1/tcp/1337",
  "--pool-type=fork-aware",
  "-lparachain=debug,xcm=trace,runtime=trace,txpool=debug,basic-authorship=debug",
]
command = "target/release/polka-storage-node"
name = "david"
validator = true
ws_port = 42068
