[package]
name = "file-storage"
version = "0.1.0"
edition.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
license-file.workspace = true
publish = false


[dependencies]
rs-car = { workspace = true }
# TODO(@jmg-duarte,15/05/2024): reduce the required features
tokio = { workspace = true, features = ["full"] }
clap = { workspace = true, features = ["derive"] }
quick-protobuf = { workspace = true }

[lints]
workspace = true
