[package]
name = "file-storage"
version = "0.1.0"
edition.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
license-file.workspace = true
publish = false


[dependencies]

[lints]
workspace = true
