[package]
name = "file-storage"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license-file.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# TODO: Use from workspace
cid = "0.11.1"
# TODO: Use from workspace
thiserror = "1.0.61"
# TODO: Use from workspace
rocksdb = "0.21"


[lints]
workspace = true
