[package]
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license-file.workspace = true
name = "polka-storage-bootstrap"
repository.workspace = true
version = "0.1.0"

[dependencies]
clap = { workspace = true, features = ["derive"] }
libp2p = { workspace = true, features = [
    "cbor",
    "dns",
    "identify",
    "kad",
    "macros",
    "noise",
    "request-response",
    "tcp",
    "tokio",
    "websocket",
    "yamux",
] }
libp2p-length-prefix-codec = { workspace = true }
primitives-p2p = { workspace = true, features = ["serde"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread", "sync", "time"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

[lints]
workspace = true
