use core::str::FromStr;

use cid::Cid;
use primitives::{
    MAX_POREP_PROOFS_PER_BLOCK, MAX_POST_PROOFS_PER_BLOCK, MAX_POST_PROOF_BYTES,
    MAX_SEAL_PROOF_BYTES,
};
use sp_core::ConstU32;
use sp_runtime::BoundedVec;

mod porep;
mod post;

pub const TEST_SEED: [u8; 16] = [
    0x59, 0x62, 0xbe, 0x5d, 0x76, 0x3d, 0x31, 0x8d, 0x17, 0xdb, 0x37, 0x32, 0x54, 0x06, 0xbc, 0xe5,
];

pub fn raw_commitment_from_hex(hex_str: &str) -> [u8; 32] {
    Cid::from_str(hex_str)
        .unwrap()
        .hash()
        .digest()
        .try_into()
        .unwrap()
}

/// Loads a proof file generated by polka-storage-provider-client either with porep or post command.
pub fn load_porep_proof_file(
    path: &str,
) -> BoundedVec<BoundedVec<u8, ConstU32<MAX_SEAL_PROOF_BYTES>>, ConstU32<MAX_POREP_PROOFS_PER_BLOCK>>
{
    std::fs::read(path)
        .unwrap()
        .chunks_exact(MAX_SEAL_PROOF_BYTES as usize)
        .map(|chunk| chunk.to_vec().try_into().unwrap())
        .collect::<Vec<_>>()
        .try_into()
        .unwrap()
}

/// Loads a proof file generated by polka-storage-provider-client either with porep or post command.
pub fn load_post_proof_file(
    path: &str,
) -> BoundedVec<BoundedVec<u8, ConstU32<MAX_POST_PROOF_BYTES>>, ConstU32<MAX_POST_PROOFS_PER_BLOCK>>
{
    std::fs::read(path)
        .unwrap()
        .chunks_exact(MAX_POST_PROOF_BYTES as usize)
        .map(|chunk| chunk.to_vec().try_into().unwrap())
        .collect::<Vec<_>>()
        .try_into()
        .unwrap()
}
