
//! Autogenerated weights for `pallet_randomness`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2024-12-23, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `parthenon`, CPU: `12th Gen Intel(R) Core(TM) i7-12700H`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// target/release/polka-storage-node
// benchmark
// pallet
// --wasm-execution=compiled
// --pallet
// pallet_randomness
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// pallets/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{constants::RocksDbWeight, Weight}};
use core::marker::PhantomData;

pub trait WeightInfo {
	fn set_author_vrf() -> Weight;
}

/// Weight functions for `pallet_randomness`.
pub struct Weights<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for Weights<T> {
	/// Storage: `ParachainSystem::ValidationData` (r:1 w:0)
	/// Proof: `ParachainSystem::ValidationData` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `ParachainSystem::RelayStateProof` (r:1 w:0)
	/// Proof: `ParachainSystem::RelayStateProof` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Randomness::CounterForAuthorVrfHistory` (r:1 w:1)
	/// Proof: `Randomness::CounterForAuthorVrfHistory` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Randomness::AuthorVrfHistory` (r:1 w:1)
	/// Proof: `Randomness::AuthorVrfHistory` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Randomness::AuthorVrf` (r:0 w:1)
	/// Proof: `Randomness::AuthorVrf` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_author_vrf() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `82`
		//  Estimated: `3547`
		// Minimum execution time: 8_891_000 picoseconds.
		Weight::from_parts(9_200_000, 0)
			.saturating_add(Weight::from_parts(0, 3547))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}
}

impl WeightInfo for () {
	/// Storage: `ParachainSystem::ValidationData` (r:1 w:0)
	/// Proof: `ParachainSystem::ValidationData` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `ParachainSystem::RelayStateProof` (r:1 w:0)
	/// Proof: `ParachainSystem::RelayStateProof` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Randomness::CounterForAuthorVrfHistory` (r:1 w:1)
	/// Proof: `Randomness::CounterForAuthorVrfHistory` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Randomness::AuthorVrfHistory` (r:1 w:1)
	/// Proof: `Randomness::AuthorVrfHistory` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Randomness::AuthorVrf` (r:0 w:1)
	/// Proof: `Randomness::AuthorVrf` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_author_vrf() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `82`
		//  Estimated: `3547`
		// Minimum execution time: 8_891_000 picoseconds.
		Weight::from_parts(9_200_000, 0)
			.saturating_add(Weight::from_parts(0, 3547))
			.saturating_add(RocksDbWeight::get().reads(4))
			.saturating_add(RocksDbWeight::get().writes(3))
	}
}
