
//! Autogenerated weights for `pallet_storage_provider`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 47.2.0
//! DATE: 2025-06-26, STEPS: `5`, REPEAT: `1`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `mac.home`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// target/release/wbuild/polka-storage-runtime/polka_storage_runtime.compact.compressed.wasm
// --pallet
// pallet_storage-provider
// --extrinsic
// *
// --steps
// 5
// --repeat
// 1
// --template
// node/benchmark_template.hbs
// --output
// pallets/storage-provider/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

pub trait WeightInfo {
    fn register_storage_provider() -> Weight;
    fn deregister_storage_provider() -> Weight;
    fn add_balance() -> Weight;
    fn withdraw_balance() -> Weight;
    fn publish_storage_deals(_n: u32, ) -> Weight;
    fn settle_deal_payments(_n: u32, ) -> Weight;
    fn publish_deal_parameters(n: u32, ) -> Weight;
    fn remove_deal_parameters() -> Weight;
    fn pre_commit_sectors() -> Weight;
    fn prove_commit_sectors() -> Weight;
    fn declare_faults() -> Weight;
    fn declare_faults_recovered() -> Weight;
    fn terminate_sectors() -> Weight;
    fn submit_windowed_post() -> Weight;
}

/// Weight functions for `pallet_storage_provider`.
pub struct Weights<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for Weights<T> {
    /// Storage: `StorageProvider::StorageProviders` (r:1 w:1)
    /// Proof: `StorageProvider::StorageProviders` (`max_values`: None, `max_size`: None, mode: `Measured`)
    fn register_storage_provider() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `6`
        //  Estimated: `3471`
        // Minimum execution time: 12_000_000 picoseconds.
        Weight::from_parts(12_000_000, 0)
            .saturating_add(Weight::from_parts(0, 3471))
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }
    /// Storage: `StorageProvider::StorageProviders` (r:1 w:1)
    /// Proof: `StorageProvider::StorageProviders` (`max_values`: None, `max_size`: None, mode: `Measured`)
    fn deregister_storage_provider() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `217`
        //  Estimated: `3682`
        // Minimum execution time: 12_000_000 picoseconds.
        Weight::from_parts(12_000_000, 0)
            .saturating_add(Weight::from_parts(0, 3682))
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }
    fn add_balance() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 1_000_000 picoseconds.
        Weight::from_parts(1_000_000, 0)
            .saturating_add(Weight::from_parts(0, 0))
    }
    fn withdraw_balance() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 1_000_000 picoseconds.
        Weight::from_parts(1_000_000, 0)
            .saturating_add(Weight::from_parts(0, 0))
    }
    /// Storage: `StorageProvider::StorageProviders` (r:1 w:0)
    /// Proof: `StorageProvider::StorageProviders` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `StorageProvider::SPDealParameters` (r:1 w:0)
    /// Proof: `StorageProvider::SPDealParameters` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `StorageProvider::PendingProposals` (r:1 w:1)
    /// Proof: `StorageProvider::PendingProposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    /// Storage: `StorageProvider::NextDealId` (r:1 w:1)
    /// Proof: `StorageProvider::NextDealId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    /// Storage: `StorageProvider::DealsForBlock` (r:1 w:1)
    /// Proof: `StorageProvider::DealsForBlock` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `StorageProvider::Proposals` (r:0 w:1)
    /// Proof: `StorageProvider::Proposals` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// The range of component `n` is `[1, 128]`.
    fn publish_storage_deals(_n: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `390`
        //  Estimated: `3855`
        // Minimum execution time: 79_000_000 picoseconds.
        Weight::from_parts(84_610_355, 0)
            .saturating_add(Weight::from_parts(0, 3855))
            .saturating_add(T::DbWeight::get().reads(5))
            .saturating_add(T::DbWeight::get().writes(4))
    }
    /// Storage: `StorageProvider::Proposals` (r:1 w:1)
    /// Proof: `StorageProvider::Proposals` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// The range of component `n` is `[1, 128]`.
    fn settle_deal_payments(_n: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `701`
        //  Estimated: `4166`
        // Minimum execution time: 53_000_000 picoseconds.
        Weight::from_parts(62_772_624, 0)
            .saturating_add(Weight::from_parts(0, 4166))
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }
    /// Storage: `StorageProvider::StorageProviders` (r:1 w:0)
    /// Proof: `StorageProvider::StorageProviders` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `StorageProvider::SPDealParameters` (r:1 w:1)
    /// Proof: `StorageProvider::SPDealParameters` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// The range of component `n` is `[1, 2]`.
    fn publish_deal_parameters(n: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `16 + n * (94 ±0)`
        //  Estimated: `3481 + n * (94 ±0)`
        // Minimum execution time: 9_000_000 picoseconds.
        Weight::from_parts(5_000_000, 0)
            .saturating_add(Weight::from_parts(0, 3481))
            // Standard Error: 1_732_050
            .saturating_add(Weight::from_parts(5_000_000, 0).saturating_mul(n.into()))
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
            .saturating_add(Weight::from_parts(0, 94).saturating_mul(n.into()))
    }
    /// Storage: `StorageProvider::StorageProviders` (r:1 w:0)
    /// Proof: `StorageProvider::StorageProviders` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `StorageProvider::SPDealParameters` (r:1 w:1)
    /// Proof: `StorageProvider::SPDealParameters` (`max_values`: None, `max_size`: None, mode: `Measured`)
    fn remove_deal_parameters() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `204`
        //  Estimated: `3669`
        // Minimum execution time: 14_000_000 picoseconds.
        Weight::from_parts(14_000_000, 0)
            .saturating_add(Weight::from_parts(0, 3669))
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }
    /// Storage: `StorageProvider::StorageProviders` (r:1 w:1)
    /// Proof: `StorageProvider::StorageProviders` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `StorageProvider::Proposals` (r:1 w:0)
    /// Proof: `StorageProvider::Proposals` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `StorageProvider::PendingProposals` (r:1 w:0)
    /// Proof: `StorageProvider::PendingProposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    fn pre_commit_sectors() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `791`
        //  Estimated: `4256`
        // Minimum execution time: 68_000_000 picoseconds.
        Weight::from_parts(68_000_000, 0)
            .saturating_add(Weight::from_parts(0, 4256))
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(1))
    }
    /// Storage: `StorageProvider::StorageProviders` (r:1 w:1)
    /// Proof: `StorageProvider::StorageProviders` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `Proofs::PoRepVerifyingKeys` (r:1 w:0)
    /// Proof: `Proofs::PoRepVerifyingKeys` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `StorageProvider::PendingProposals` (r:1 w:1)
    /// Proof: `StorageProvider::PendingProposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    /// Storage: `StorageProvider::Proposals` (r:1 w:1)
    /// Proof: `StorageProvider::Proposals` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `StorageProvider::SectorDeals` (r:0 w:1)
    /// Proof: `StorageProvider::SectorDeals` (`max_values`: None, `max_size`: None, mode: `Measured`)
    fn prove_commit_sectors() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `17251`
        //  Estimated: `20716`
        // Minimum execution time: 932_947_000_000 picoseconds.
        Weight::from_parts(932_947_000_000, 0)
            .saturating_add(Weight::from_parts(0, 20716))
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().writes(4))
    }
    /// Storage: `StorageProvider::StorageProviders` (r:1 w:1)
    /// Proof: `StorageProvider::StorageProviders` (`max_values`: None, `max_size`: None, mode: `Measured`)
    fn declare_faults() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `502`
        //  Estimated: `3967`
        // Minimum execution time: 51_000_000 picoseconds.
        Weight::from_parts(51_000_000, 0)
            .saturating_add(Weight::from_parts(0, 3967))
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }
    /// Storage: `StorageProvider::StorageProviders` (r:1 w:1)
    /// Proof: `StorageProvider::StorageProviders` (`max_values`: None, `max_size`: None, mode: `Measured`)
    fn declare_faults_recovered() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `502`
        //  Estimated: `3967`
        // Minimum execution time: 34_000_000 picoseconds.
        Weight::from_parts(34_000_000, 0)
            .saturating_add(Weight::from_parts(0, 3967))
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }
    /// Storage: `StorageProvider::StorageProviders` (r:1 w:1)
    /// Proof: `StorageProvider::StorageProviders` (`max_values`: None, `max_size`: None, mode: `Measured`)
    fn terminate_sectors() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `502`
        //  Estimated: `3967`
        // Minimum execution time: 71_000_000 picoseconds.
        Weight::from_parts(71_000_000, 0)
            .saturating_add(Weight::from_parts(0, 3967))
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }
    /// Storage: `StorageProvider::StorageProviders` (r:1 w:1)
    /// Proof: `StorageProvider::StorageProviders` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `Proofs::PoStVerifyingKeys` (r:1 w:0)
    /// Proof: `Proofs::PoStVerifyingKeys` (`max_values`: None, `max_size`: None, mode: `Measured`)
    fn submit_windowed_post() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `14274`
        //  Estimated: `17739`
        // Minimum execution time: 647_368_000_000 picoseconds.
        Weight::from_parts(647_368_000_000, 0)
            .saturating_add(Weight::from_parts(0, 17739))
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }
}

impl WeightInfo for () {
    /// Storage: `StorageProvider::StorageProviders` (r:1 w:1)
    /// Proof: `StorageProvider::StorageProviders` (`max_values`: None, `max_size`: None, mode: `Measured`)
    fn register_storage_provider() -> Weight {
        use frame_support::weights::constants::RocksDbWeight;

        // Proof Size summary in bytes:
        //  Measured:  `6`
        //  Estimated: `3471`
        // Minimum execution time: 12_000_000 picoseconds.
        Weight::from_parts(12_000_000, 0)
            .saturating_add(Weight::from_parts(0, 3471))
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    /// Storage: `StorageProvider::StorageProviders` (r:1 w:1)
    /// Proof: `StorageProvider::StorageProviders` (`max_values`: None, `max_size`: None, mode: `Measured`)
    fn deregister_storage_provider() -> Weight {
        use frame_support::weights::constants::RocksDbWeight;

        // Proof Size summary in bytes:
        //  Measured:  `217`
        //  Estimated: `3682`
        // Minimum execution time: 12_000_000 picoseconds.
        Weight::from_parts(12_000_000, 0)
            .saturating_add(Weight::from_parts(0, 3682))
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn add_balance() -> Weight {
        use frame_support::weights::constants::RocksDbWeight;

        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 1_000_000 picoseconds.
        Weight::from_parts(1_000_000, 0)
            .saturating_add(Weight::from_parts(0, 0))
    }
    fn withdraw_balance() -> Weight {
        use frame_support::weights::constants::RocksDbWeight;

        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 1_000_000 picoseconds.
        Weight::from_parts(1_000_000, 0)
            .saturating_add(Weight::from_parts(0, 0))
    }
    /// Storage: `StorageProvider::StorageProviders` (r:1 w:0)
    /// Proof: `StorageProvider::StorageProviders` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `StorageProvider::SPDealParameters` (r:1 w:0)
    /// Proof: `StorageProvider::SPDealParameters` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `StorageProvider::PendingProposals` (r:1 w:1)
    /// Proof: `StorageProvider::PendingProposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    /// Storage: `StorageProvider::NextDealId` (r:1 w:1)
    /// Proof: `StorageProvider::NextDealId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    /// Storage: `StorageProvider::DealsForBlock` (r:1 w:1)
    /// Proof: `StorageProvider::DealsForBlock` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `StorageProvider::Proposals` (r:0 w:1)
    /// Proof: `StorageProvider::Proposals` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// The range of component `n` is `[1, 128]`.
    fn publish_storage_deals(_n: u32, ) -> Weight {
        use frame_support::weights::constants::RocksDbWeight;

        // Proof Size summary in bytes:
        //  Measured:  `390`
        //  Estimated: `3855`
        // Minimum execution time: 79_000_000 picoseconds.
        Weight::from_parts(84_610_355, 0)
            .saturating_add(Weight::from_parts(0, 3855))
            .saturating_add(RocksDbWeight::get().reads(5))
            .saturating_add(RocksDbWeight::get().writes(4))
    }
    /// Storage: `StorageProvider::Proposals` (r:1 w:1)
    /// Proof: `StorageProvider::Proposals` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// The range of component `n` is `[1, 128]`.
    fn settle_deal_payments(_n: u32, ) -> Weight {
        use frame_support::weights::constants::RocksDbWeight;

        // Proof Size summary in bytes:
        //  Measured:  `701`
        //  Estimated: `4166`
        // Minimum execution time: 53_000_000 picoseconds.
        Weight::from_parts(62_772_624, 0)
            .saturating_add(Weight::from_parts(0, 4166))
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    /// Storage: `StorageProvider::StorageProviders` (r:1 w:0)
    /// Proof: `StorageProvider::StorageProviders` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `StorageProvider::SPDealParameters` (r:1 w:1)
    /// Proof: `StorageProvider::SPDealParameters` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// The range of component `n` is `[1, 2]`.
    fn publish_deal_parameters(n: u32, ) -> Weight {
        use frame_support::weights::constants::RocksDbWeight;

        // Proof Size summary in bytes:
        //  Measured:  `16 + n * (94 ±0)`
        //  Estimated: `3481 + n * (94 ±0)`
        // Minimum execution time: 9_000_000 picoseconds.
        Weight::from_parts(5_000_000, 0)
            .saturating_add(Weight::from_parts(0, 3481))
            // Standard Error: 1_732_050
            .saturating_add(Weight::from_parts(5_000_000, 0).saturating_mul(n.into()))
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(1))
            .saturating_add(Weight::from_parts(0, 94).saturating_mul(n.into()))
    }
    /// Storage: `StorageProvider::StorageProviders` (r:1 w:0)
    /// Proof: `StorageProvider::StorageProviders` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `StorageProvider::SPDealParameters` (r:1 w:1)
    /// Proof: `StorageProvider::SPDealParameters` (`max_values`: None, `max_size`: None, mode: `Measured`)
    fn remove_deal_parameters() -> Weight {
        use frame_support::weights::constants::RocksDbWeight;

        // Proof Size summary in bytes:
        //  Measured:  `204`
        //  Estimated: `3669`
        // Minimum execution time: 14_000_000 picoseconds.
        Weight::from_parts(14_000_000, 0)
            .saturating_add(Weight::from_parts(0, 3669))
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    /// Storage: `StorageProvider::StorageProviders` (r:1 w:1)
    /// Proof: `StorageProvider::StorageProviders` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `StorageProvider::Proposals` (r:1 w:0)
    /// Proof: `StorageProvider::Proposals` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `StorageProvider::PendingProposals` (r:1 w:0)
    /// Proof: `StorageProvider::PendingProposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    fn pre_commit_sectors() -> Weight {
        use frame_support::weights::constants::RocksDbWeight;

        // Proof Size summary in bytes:
        //  Measured:  `791`
        //  Estimated: `4256`
        // Minimum execution time: 68_000_000 picoseconds.
        Weight::from_parts(68_000_000, 0)
            .saturating_add(Weight::from_parts(0, 4256))
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    /// Storage: `StorageProvider::StorageProviders` (r:1 w:1)
    /// Proof: `StorageProvider::StorageProviders` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `Proofs::PoRepVerifyingKeys` (r:1 w:0)
    /// Proof: `Proofs::PoRepVerifyingKeys` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `StorageProvider::PendingProposals` (r:1 w:1)
    /// Proof: `StorageProvider::PendingProposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    /// Storage: `StorageProvider::Proposals` (r:1 w:1)
    /// Proof: `StorageProvider::Proposals` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `StorageProvider::SectorDeals` (r:0 w:1)
    /// Proof: `StorageProvider::SectorDeals` (`max_values`: None, `max_size`: None, mode: `Measured`)
    fn prove_commit_sectors() -> Weight {
        use frame_support::weights::constants::RocksDbWeight;

        // Proof Size summary in bytes:
        //  Measured:  `17251`
        //  Estimated: `20716`
        // Minimum execution time: 932_947_000_000 picoseconds.
        Weight::from_parts(932_947_000_000, 0)
            .saturating_add(Weight::from_parts(0, 20716))
            .saturating_add(RocksDbWeight::get().reads(4))
            .saturating_add(RocksDbWeight::get().writes(4))
    }
    /// Storage: `StorageProvider::StorageProviders` (r:1 w:1)
    /// Proof: `StorageProvider::StorageProviders` (`max_values`: None, `max_size`: None, mode: `Measured`)
    fn declare_faults() -> Weight {
        use frame_support::weights::constants::RocksDbWeight;

        // Proof Size summary in bytes:
        //  Measured:  `502`
        //  Estimated: `3967`
        // Minimum execution time: 51_000_000 picoseconds.
        Weight::from_parts(51_000_000, 0)
            .saturating_add(Weight::from_parts(0, 3967))
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    /// Storage: `StorageProvider::StorageProviders` (r:1 w:1)
    /// Proof: `StorageProvider::StorageProviders` (`max_values`: None, `max_size`: None, mode: `Measured`)
    fn declare_faults_recovered() -> Weight {
        use frame_support::weights::constants::RocksDbWeight;

        // Proof Size summary in bytes:
        //  Measured:  `502`
        //  Estimated: `3967`
        // Minimum execution time: 34_000_000 picoseconds.
        Weight::from_parts(34_000_000, 0)
            .saturating_add(Weight::from_parts(0, 3967))
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    /// Storage: `StorageProvider::StorageProviders` (r:1 w:1)
    /// Proof: `StorageProvider::StorageProviders` (`max_values`: None, `max_size`: None, mode: `Measured`)
    fn terminate_sectors() -> Weight {
        use frame_support::weights::constants::RocksDbWeight;

        // Proof Size summary in bytes:
        //  Measured:  `502`
        //  Estimated: `3967`
        // Minimum execution time: 71_000_000 picoseconds.
        Weight::from_parts(71_000_000, 0)
            .saturating_add(Weight::from_parts(0, 3967))
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    /// Storage: `StorageProvider::StorageProviders` (r:1 w:1)
    /// Proof: `StorageProvider::StorageProviders` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `Proofs::PoStVerifyingKeys` (r:1 w:0)
    /// Proof: `Proofs::PoStVerifyingKeys` (`max_values`: None, `max_size`: None, mode: `Measured`)
    fn submit_windowed_post() -> Weight {
        use frame_support::weights::constants::RocksDbWeight;

        // Proof Size summary in bytes:
        //  Measured:  `14274`
        //  Estimated: `17739`
        // Minimum execution time: 647_368_000_000 picoseconds.
        Weight::from_parts(647_368_000_000, 0)
            .saturating_add(Weight::from_parts(0, 17739))
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
}
