
//! Autogenerated weights for `pallet_storage_provider`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2025-06-05, STEPS: `5`, REPEAT: `1`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `DESKTOP-IOP6PE6`, CPU: `AMD Ryzen 9 5950X 16-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// target/release/polka-storage-node
// benchmark
// pallet
// --wasm-execution=compiled
// --pallet
// pallet_storage-provider
// --extrinsic
// *
// --steps
// 5
// --repeat
// 1
// --template
// node/benchmark_template.hbs
// --output
// pallets/storage-provider/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

pub trait WeightInfo {
    fn register_storage_provider() -> Weight;
    fn add_balance() -> Weight;
    fn withdraw_balance() -> Weight;
    fn publish_storage_deals(_n: u32, ) -> Weight;
    fn settle_deal_payments(_n: u32, ) -> Weight;
    fn publish_deal_parameters(n: u32, ) -> Weight;
    fn remove_deal_parameters() -> Weight;
    fn pre_commit_sectors() -> Weight;
    fn prove_commit_sectors() -> Weight;
    fn declare_faults() -> Weight;
    fn declare_faults_recovered() -> Weight;
    fn terminate_sectors() -> Weight;
    fn submit_windowed_post() -> Weight;
}

/// Weight functions for `pallet_storage_provider`.
pub struct Weights<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for Weights<T> {
    /// Storage: `StorageProvider::StorageProviders` (r:1 w:1)
    /// Proof: `StorageProvider::StorageProviders` (`max_values`: None, `max_size`: None, mode: `Measured`)
    fn register_storage_provider() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `43`
        //  Estimated: `3508`
        // Minimum execution time: 20_183_000 picoseconds.
        Weight::from_parts(20_183_000, 0)
            .saturating_add(Weight::from_parts(0, 3508))
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }
    /// Storage: `StorageProvider::BalanceTable` (r:1 w:1)
    /// Proof: `StorageProvider::BalanceTable` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `System::Account` (r:1 w:1)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    fn add_balance() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `222`
        //  Estimated: `3687`
        // Minimum execution time: 61_337_000 picoseconds.
        Weight::from_parts(61_337_000, 0)
            .saturating_add(Weight::from_parts(0, 3687))
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(2))
    }
    /// Storage: `StorageProvider::BalanceTable` (r:1 w:1)
    /// Proof: `StorageProvider::BalanceTable` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `System::Account` (r:1 w:1)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    fn withdraw_balance() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `394`
        //  Estimated: `3859`
        // Minimum execution time: 62_595_000 picoseconds.
        Weight::from_parts(62_595_000, 0)
            .saturating_add(Weight::from_parts(0, 3859))
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(2))
    }
    /// Storage: `StorageProvider::StorageProviders` (r:1 w:0)
    /// Proof: `StorageProvider::StorageProviders` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `StorageProvider::SPDealParameters` (r:1 w:0)
    /// Proof: `StorageProvider::SPDealParameters` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `StorageProvider::BalanceTable` (r:2 w:2)
    /// Proof: `StorageProvider::BalanceTable` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `StorageProvider::PendingProposals` (r:1 w:1)
    /// Proof: `StorageProvider::PendingProposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    /// Storage: `StorageProvider::NextDealId` (r:1 w:1)
    /// Proof: `StorageProvider::NextDealId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    /// Storage: `StorageProvider::DealsForBlock` (r:1 w:1)
    /// Proof: `StorageProvider::DealsForBlock` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `StorageProvider::Proposals` (r:0 w:1)
    /// Proof: `StorageProvider::Proposals` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// The range of component `n` is `[1, 128]`.
    fn publish_storage_deals(_n: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `407`
        //  Estimated: `6347`
        // Minimum execution time: 86_632_000 picoseconds.
        Weight::from_parts(90_706_325, 0)
            .saturating_add(Weight::from_parts(0, 6347))
            .saturating_add(T::DbWeight::get().reads(7))
            .saturating_add(T::DbWeight::get().writes(6))
    }
    /// Storage: `StorageProvider::Proposals` (r:1 w:1)
    /// Proof: `StorageProvider::Proposals` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `StorageProvider::BalanceTable` (r:2 w:2)
    /// Proof: `StorageProvider::BalanceTable` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// The range of component `n` is `[1, 128]`.
    fn settle_deal_payments(_n: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `730`
        //  Estimated: `6670`
        // Minimum execution time: 35_785_000 picoseconds.
        Weight::from_parts(53_340_317, 0)
            .saturating_add(Weight::from_parts(0, 6670))
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(3))
    }
    /// Storage: `StorageProvider::StorageProviders` (r:1 w:0)
    /// Proof: `StorageProvider::StorageProviders` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `StorageProvider::SPDealParameters` (r:1 w:1)
    /// Proof: `StorageProvider::SPDealParameters` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// The range of component `n` is `[1, 2]`.
    fn publish_deal_parameters(n: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `42 + n * (102 ±0)`
        //  Estimated: `3507 + n * (102 ±0)`
        // Minimum execution time: 15_707_000 picoseconds.
        Weight::from_parts(16_630_000, 0)
            .saturating_add(Weight::from_parts(0, 3507))
            // Standard Error: 1_111_110
            .saturating_add(Weight::from_parts(99_500, 0).saturating_mul(n.into()))
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
            .saturating_add(Weight::from_parts(0, 102).saturating_mul(n.into()))
    }
    /// Storage: `StorageProvider::StorageProviders` (r:1 w:0)
    /// Proof: `StorageProvider::StorageProviders` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `StorageProvider::SPDealParameters` (r:1 w:1)
    /// Proof: `StorageProvider::SPDealParameters` (`max_values`: None, `max_size`: None, mode: `Measured`)
    fn remove_deal_parameters() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `246`
        //  Estimated: `3711`
        // Minimum execution time: 17_382_000 picoseconds.
        Weight::from_parts(17_382_000, 0)
            .saturating_add(Weight::from_parts(0, 3711))
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }
    /// Storage: `StorageProvider::StorageProviders` (r:1 w:1)
    /// Proof: `StorageProvider::StorageProviders` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `StorageProvider::Proposals` (r:1 w:0)
    /// Proof: `StorageProvider::Proposals` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `StorageProvider::PendingProposals` (r:1 w:0)
    /// Proof: `StorageProvider::PendingProposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    /// Storage: `StorageProvider::BalanceTable` (r:1 w:1)
    /// Proof: `StorageProvider::BalanceTable` (`max_values`: None, `max_size`: None, mode: `Measured`)
    fn pre_commit_sectors() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `874`
        //  Estimated: `4339`
        // Minimum execution time: 58_900_000 picoseconds.
        Weight::from_parts(58_900_000, 0)
            .saturating_add(Weight::from_parts(0, 4339))
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().writes(2))
    }
    /// Storage: `StorageProvider::StorageProviders` (r:1 w:1)
    /// Proof: `StorageProvider::StorageProviders` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `Proofs::PoRepVerifyingKeys` (r:1 w:0)
    /// Proof: `Proofs::PoRepVerifyingKeys` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `StorageProvider::PendingProposals` (r:1 w:1)
    /// Proof: `StorageProvider::PendingProposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    /// Storage: `StorageProvider::Proposals` (r:1 w:1)
    /// Proof: `StorageProvider::Proposals` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `StorageProvider::BalanceTable` (r:1 w:1)
    /// Proof: `StorageProvider::BalanceTable` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `StorageProvider::SectorDeals` (r:0 w:1)
    /// Proof: `StorageProvider::SectorDeals` (`max_values`: None, `max_size`: None, mode: `Measured`)
    fn prove_commit_sectors() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `17346`
        //  Estimated: `20811`
        // Minimum execution time: 1_305_421_095_000 picoseconds.
        Weight::from_parts(1_305_421_095_000, 0)
            .saturating_add(Weight::from_parts(0, 20811))
            .saturating_add(T::DbWeight::get().reads(5))
            .saturating_add(T::DbWeight::get().writes(5))
    }
    /// Storage: `StorageProvider::StorageProviders` (r:1 w:1)
    /// Proof: `StorageProvider::StorageProviders` (`max_values`: None, `max_size`: None, mode: `Measured`)
    fn declare_faults() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `555`
        //  Estimated: `4020`
        // Minimum execution time: 52_192_000 picoseconds.
        Weight::from_parts(52_192_000, 0)
            .saturating_add(Weight::from_parts(0, 4020))
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }
    /// Storage: `StorageProvider::StorageProviders` (r:1 w:1)
    /// Proof: `StorageProvider::StorageProviders` (`max_values`: None, `max_size`: None, mode: `Measured`)
    fn declare_faults_recovered() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `555`
        //  Estimated: `4020`
        // Minimum execution time: 35_551_000 picoseconds.
        Weight::from_parts(35_551_000, 0)
            .saturating_add(Weight::from_parts(0, 4020))
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }
    /// Storage: `StorageProvider::StorageProviders` (r:1 w:1)
    /// Proof: `StorageProvider::StorageProviders` (`max_values`: None, `max_size`: None, mode: `Measured`)
    fn terminate_sectors() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `555`
        //  Estimated: `4020`
        // Minimum execution time: 73_633_000 picoseconds.
        Weight::from_parts(73_633_000, 0)
            .saturating_add(Weight::from_parts(0, 4020))
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }
    /// Storage: `StorageProvider::StorageProviders` (r:1 w:1)
    /// Proof: `StorageProvider::StorageProviders` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `Proofs::PoStVerifyingKeys` (r:1 w:0)
    /// Proof: `Proofs::PoStVerifyingKeys` (`max_values`: None, `max_size`: None, mode: `Measured`)
    fn submit_windowed_post() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `14327`
        //  Estimated: `17792`
        // Minimum execution time: 967_180_582_000 picoseconds.
        Weight::from_parts(967_180_582_000, 0)
            .saturating_add(Weight::from_parts(0, 17792))
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }
}

impl WeightInfo for () {
    /// Storage: `StorageProvider::StorageProviders` (r:1 w:1)
    /// Proof: `StorageProvider::StorageProviders` (`max_values`: None, `max_size`: None, mode: `Measured`)
    fn register_storage_provider() -> Weight {
        use frame_support::weights::constants::RocksDbWeight;

        // Proof Size summary in bytes:
        //  Measured:  `43`
        //  Estimated: `3508`
        // Minimum execution time: 20_183_000 picoseconds.
        Weight::from_parts(20_183_000, 0)
            .saturating_add(Weight::from_parts(0, 3508))
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    /// Storage: `StorageProvider::BalanceTable` (r:1 w:1)
    /// Proof: `StorageProvider::BalanceTable` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `System::Account` (r:1 w:1)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    fn add_balance() -> Weight {
        use frame_support::weights::constants::RocksDbWeight;

        // Proof Size summary in bytes:
        //  Measured:  `222`
        //  Estimated: `3687`
        // Minimum execution time: 61_337_000 picoseconds.
        Weight::from_parts(61_337_000, 0)
            .saturating_add(Weight::from_parts(0, 3687))
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(2))
    }
    /// Storage: `StorageProvider::BalanceTable` (r:1 w:1)
    /// Proof: `StorageProvider::BalanceTable` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `System::Account` (r:1 w:1)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    fn withdraw_balance() -> Weight {
        use frame_support::weights::constants::RocksDbWeight;

        // Proof Size summary in bytes:
        //  Measured:  `394`
        //  Estimated: `3859`
        // Minimum execution time: 62_595_000 picoseconds.
        Weight::from_parts(62_595_000, 0)
            .saturating_add(Weight::from_parts(0, 3859))
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(2))
    }
    /// Storage: `StorageProvider::StorageProviders` (r:1 w:0)
    /// Proof: `StorageProvider::StorageProviders` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `StorageProvider::SPDealParameters` (r:1 w:0)
    /// Proof: `StorageProvider::SPDealParameters` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `StorageProvider::BalanceTable` (r:2 w:2)
    /// Proof: `StorageProvider::BalanceTable` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `StorageProvider::PendingProposals` (r:1 w:1)
    /// Proof: `StorageProvider::PendingProposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    /// Storage: `StorageProvider::NextDealId` (r:1 w:1)
    /// Proof: `StorageProvider::NextDealId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    /// Storage: `StorageProvider::DealsForBlock` (r:1 w:1)
    /// Proof: `StorageProvider::DealsForBlock` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `StorageProvider::Proposals` (r:0 w:1)
    /// Proof: `StorageProvider::Proposals` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// The range of component `n` is `[1, 128]`.
    fn publish_storage_deals(_n: u32, ) -> Weight {
        use frame_support::weights::constants::RocksDbWeight;

        // Proof Size summary in bytes:
        //  Measured:  `407`
        //  Estimated: `6347`
        // Minimum execution time: 86_632_000 picoseconds.
        Weight::from_parts(90_706_325, 0)
            .saturating_add(Weight::from_parts(0, 6347))
            .saturating_add(RocksDbWeight::get().reads(7))
            .saturating_add(RocksDbWeight::get().writes(6))
    }
    /// Storage: `StorageProvider::Proposals` (r:1 w:1)
    /// Proof: `StorageProvider::Proposals` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `StorageProvider::BalanceTable` (r:2 w:2)
    /// Proof: `StorageProvider::BalanceTable` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// The range of component `n` is `[1, 128]`.
    fn settle_deal_payments(_n: u32, ) -> Weight {
        use frame_support::weights::constants::RocksDbWeight;

        // Proof Size summary in bytes:
        //  Measured:  `730`
        //  Estimated: `6670`
        // Minimum execution time: 35_785_000 picoseconds.
        Weight::from_parts(53_340_317, 0)
            .saturating_add(Weight::from_parts(0, 6670))
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().writes(3))
    }
    /// Storage: `StorageProvider::StorageProviders` (r:1 w:0)
    /// Proof: `StorageProvider::StorageProviders` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `StorageProvider::SPDealParameters` (r:1 w:1)
    /// Proof: `StorageProvider::SPDealParameters` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// The range of component `n` is `[1, 2]`.
    fn publish_deal_parameters(n: u32, ) -> Weight {
        use frame_support::weights::constants::RocksDbWeight;

        // Proof Size summary in bytes:
        //  Measured:  `42 + n * (102 ±0)`
        //  Estimated: `3507 + n * (102 ±0)`
        // Minimum execution time: 15_707_000 picoseconds.
        Weight::from_parts(16_630_000, 0)
            .saturating_add(Weight::from_parts(0, 3507))
            // Standard Error: 1_111_110
            .saturating_add(Weight::from_parts(99_500, 0).saturating_mul(n.into()))
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(1))
            .saturating_add(Weight::from_parts(0, 102).saturating_mul(n.into()))
    }
    /// Storage: `StorageProvider::StorageProviders` (r:1 w:0)
    /// Proof: `StorageProvider::StorageProviders` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `StorageProvider::SPDealParameters` (r:1 w:1)
    /// Proof: `StorageProvider::SPDealParameters` (`max_values`: None, `max_size`: None, mode: `Measured`)
    fn remove_deal_parameters() -> Weight {
        use frame_support::weights::constants::RocksDbWeight;

        // Proof Size summary in bytes:
        //  Measured:  `246`
        //  Estimated: `3711`
        // Minimum execution time: 17_382_000 picoseconds.
        Weight::from_parts(17_382_000, 0)
            .saturating_add(Weight::from_parts(0, 3711))
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    /// Storage: `StorageProvider::StorageProviders` (r:1 w:1)
    /// Proof: `StorageProvider::StorageProviders` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `StorageProvider::Proposals` (r:1 w:0)
    /// Proof: `StorageProvider::Proposals` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `StorageProvider::PendingProposals` (r:1 w:0)
    /// Proof: `StorageProvider::PendingProposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    /// Storage: `StorageProvider::BalanceTable` (r:1 w:1)
    /// Proof: `StorageProvider::BalanceTable` (`max_values`: None, `max_size`: None, mode: `Measured`)
    fn pre_commit_sectors() -> Weight {
        use frame_support::weights::constants::RocksDbWeight;

        // Proof Size summary in bytes:
        //  Measured:  `874`
        //  Estimated: `4339`
        // Minimum execution time: 58_900_000 picoseconds.
        Weight::from_parts(58_900_000, 0)
            .saturating_add(Weight::from_parts(0, 4339))
            .saturating_add(RocksDbWeight::get().reads(4))
            .saturating_add(RocksDbWeight::get().writes(2))
    }
    /// Storage: `StorageProvider::StorageProviders` (r:1 w:1)
    /// Proof: `StorageProvider::StorageProviders` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `Proofs::PoRepVerifyingKeys` (r:1 w:0)
    /// Proof: `Proofs::PoRepVerifyingKeys` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `StorageProvider::PendingProposals` (r:1 w:1)
    /// Proof: `StorageProvider::PendingProposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    /// Storage: `StorageProvider::Proposals` (r:1 w:1)
    /// Proof: `StorageProvider::Proposals` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `StorageProvider::BalanceTable` (r:1 w:1)
    /// Proof: `StorageProvider::BalanceTable` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `StorageProvider::SectorDeals` (r:0 w:1)
    /// Proof: `StorageProvider::SectorDeals` (`max_values`: None, `max_size`: None, mode: `Measured`)
    fn prove_commit_sectors() -> Weight {
        use frame_support::weights::constants::RocksDbWeight;

        // Proof Size summary in bytes:
        //  Measured:  `17346`
        //  Estimated: `20811`
        // Minimum execution time: 1_305_421_095_000 picoseconds.
        Weight::from_parts(1_305_421_095_000, 0)
            .saturating_add(Weight::from_parts(0, 20811))
            .saturating_add(RocksDbWeight::get().reads(5))
            .saturating_add(RocksDbWeight::get().writes(5))
    }
    /// Storage: `StorageProvider::StorageProviders` (r:1 w:1)
    /// Proof: `StorageProvider::StorageProviders` (`max_values`: None, `max_size`: None, mode: `Measured`)
    fn declare_faults() -> Weight {
        use frame_support::weights::constants::RocksDbWeight;

        // Proof Size summary in bytes:
        //  Measured:  `555`
        //  Estimated: `4020`
        // Minimum execution time: 52_192_000 picoseconds.
        Weight::from_parts(52_192_000, 0)
            .saturating_add(Weight::from_parts(0, 4020))
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    /// Storage: `StorageProvider::StorageProviders` (r:1 w:1)
    /// Proof: `StorageProvider::StorageProviders` (`max_values`: None, `max_size`: None, mode: `Measured`)
    fn declare_faults_recovered() -> Weight {
        use frame_support::weights::constants::RocksDbWeight;

        // Proof Size summary in bytes:
        //  Measured:  `555`
        //  Estimated: `4020`
        // Minimum execution time: 35_551_000 picoseconds.
        Weight::from_parts(35_551_000, 0)
            .saturating_add(Weight::from_parts(0, 4020))
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    /// Storage: `StorageProvider::StorageProviders` (r:1 w:1)
    /// Proof: `StorageProvider::StorageProviders` (`max_values`: None, `max_size`: None, mode: `Measured`)
    fn terminate_sectors() -> Weight {
        use frame_support::weights::constants::RocksDbWeight;

        // Proof Size summary in bytes:
        //  Measured:  `555`
        //  Estimated: `4020`
        // Minimum execution time: 73_633_000 picoseconds.
        Weight::from_parts(73_633_000, 0)
            .saturating_add(Weight::from_parts(0, 4020))
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    /// Storage: `StorageProvider::StorageProviders` (r:1 w:1)
    /// Proof: `StorageProvider::StorageProviders` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `Proofs::PoStVerifyingKeys` (r:1 w:0)
    /// Proof: `Proofs::PoStVerifyingKeys` (`max_values`: None, `max_size`: None, mode: `Measured`)
    fn submit_windowed_post() -> Weight {
        use frame_support::weights::constants::RocksDbWeight;

        // Proof Size summary in bytes:
        //  Measured:  `14327`
        //  Estimated: `17792`
        // Minimum execution time: 967_180_582_000 picoseconds.
        Weight::from_parts(967_180_582_000, 0)
            .saturating_add(Weight::from_parts(0, 17792))
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
}
