[relaychain]
default_command = "polkadot"
chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"
  validator = true

  [[relaychain.nodes]]
  name = "bob"
  validator = true

[[parachains]]
id = 2000
cumulus_based = true

  # run charlie as parachain collator
  [[parachains.collators]]
  name = "charlie"
  validator = true
  command = "target/release/polka-storage-node"