name: CI

on:
  pull_request:
    types:
    # These are the default types
    - opened
    - synchronize
    - reopened
    # This additional type is added to trigger on the 'ready for review' label being added
    - labeled
  push:
    branches: [develop, main]
  workflow_dispatch: # manual launch

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-files:
    runs-on: self-hosted
    outputs:
      skip: ${{ steps.check-files.outputs.skip }}
    steps:
      - uses: actions/checkout@v4
      - uses: tj-actions/changed-files@c65cd883420fd2eb864698a825fc4162dd94482c #v44.5.7
        id: changed-files
        with:
          files: |
            **/*.rs
            **/Cargo.toml
            **/*.scale
      - name: Check if proper files changed
        id: check-files
        run: |
          if [[ "${{ steps.changed-files.outputs.any_changed }}" == "false" ]]; then
            echo "No files changed. Skipping CI."
            echo "skip=true" >> "$GITHUB_OUTPUT"
          else
            echo "Some files changed. Running CI."
            echo "skip=false" >> "$GITHUB_OUTPUT"
          fi

  docs:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: "0.4.40"
      - name: Build the book
        run: mdbook build docs

  toml:
    if: ${{ needs.check-files.outputs.skip == 'false' && (contains(github.event.pull_request.labels.*.name, 'ready for review') || (github.ref_name == 'develop') || (github.ref_name == 'master')) }}
    runs-on: self-hosted
    needs: check-files
    steps:
      - uses: actions/checkout@v4
      - name: List versions
        run: |
          cargo --version
          taplo --version
      - name: Run taplo
        run: |
          taplo lint
          taplo fmt --check

  format:
    runs-on: self-hosted
    needs: toml
    steps:
      - uses: actions/checkout@v4
      - name: List version
        run: |
          cargo +nightly --version
          cargo +nightly fmt --version
      - name: Cargo format
        run: cargo +nightly fmt --all -- --check

  clippy_build_and_test:
    runs-on: self-hosted
    needs:
      - format
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v4
      - name: List version
        run: |
          rustup show
          cargo --version
          cargo clippy --version
          cargo tarpaulin --version
      - name: Build in dev mode
        run: cargo build --profile ci --locked
      - name: Cargo clippy
        run: cargo clippy --profile ci --locked
      - name: Run tests
        run: cargo tarpaulin --profile ci --locked --workspace --skip-clean --exclude maat

  benchmarks:
    runs-on: self-hosted
    needs:
      - clippy_build_and_test
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v4

      - name: pallet-proofs — Run test benchmarks
        run: cargo test --profile ci --locked -p pallet-proofs --features runtime-benchmarks -- benchmark --nocapture

      - name: pallet-proofs — Run node benchmarks
        run: |
          cargo run \
          -p polka-storage-node --bin polka-storage-node -r -F runtime-benchmarks -- \
          benchmark pallet \
          --wasm-execution=compiled \
          --pallet "pallet_proofs" \
          --extrinsic "*" \
          --steps 5 \
          --repeat 1 \
          --template node/benchmark_template.hbs

      - name: pallet-randomness — Run test benchmarks
        run: cargo test --profile ci --locked -p pallet-randomness --features runtime-benchmarks -- benchmark --nocapture

      - name: pallet-randomness — Run node benchmarks
        run: |
          cargo run \
          -p polka-storage-node --bin polka-storage-node -r -F runtime-benchmarks -- \
          benchmark pallet \
          --wasm-execution=compiled \
          --pallet "pallet_randomness" \
          --extrinsic "*" \
          --steps 5 \
          --repeat 1 \
          --template node/benchmark_template.hbs

      - name: pallet-market — Run test benchmarks
        run: cargo test --profile ci --locked -p pallet-market-benchmarks --features runtime-benchmarks -- benchmark --nocapture

      - name: pallet-market — Run node benchmarks
        run: |
          cargo run \
          -p polka-storage-node --bin polka-storage-node -r -F runtime-benchmarks -F testnet -- \
          benchmark pallet \
          --wasm-execution=compiled \
          --pallet "pallet_market" \
          --extrinsic "*" \
          --steps 5 \
          --repeat 1 \
          --template node/benchmark_template.hbs

      - name: pallet-storage-provider — Run test benchmarks
        run: cargo test --profile ci --locked -p pallet-storage-provider-benchmarks --features runtime-benchmarks -- benchmark --nocapture

      - name: pallet-storage-provider — Run node benchmarks
        run: |
          cargo run \
          -p polka-storage-node --bin polka-storage-node -r -F runtime-benchmarks -F testnet -- \
          benchmark pallet \
          --wasm-execution=compiled \
          --pallet "pallet_storage_provider" \
          --extrinsic "*" \
          --steps 5 \
          --repeat 1 \
          --template node/benchmark_template.hbs
