name: CI

on:
  pull_request:
    types: [ labeled ]
  push:
    branches: [ develop, main ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  toml:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: List versions
        run: |
          cargo --version
          taplo --version
      - name: Run taplo
        run: |
          taplo lint
          taplo fmt --check

  format:
    runs-on: self-hosted
    needs: toml
    steps:
      - uses: actions/checkout@v4
      - name: List version
        run: |
          cargo +nightly --version
          cargo +nightly fmt --version
      - name: Cargo format
        run: cargo +nightly fmt --all -- --check

  clippy_build_and_test:
    runs-on: self-hosted
    needs:
      - format
    steps:
      - uses: actions/checkout@v4
      - name: List version
        run: |
          rustup show
          cargo --version
          cargo clippy --version
      - name: Build in dev mode
        run: RUSTFLAGS="-D warnings" cargo build --profile ci --locked
      - name: Cargo clippy
        run: RUSTFLAGS="-D warnings" cargo clippy --profile ci --locked
      - name: Run tests
        run: RUSTFLAGS="-D warnings" cargo test --profile ci --locked --workspace
      # FIXME(#35,@serhii,27/5/2024): Revert the commit from the issue to restore the full set of CI steps.
