name: Taplo formatting

on:
  push:
    paths: "**/*.toml"
  pull_request:
    paths: "**/*.toml"

jobs:
  toml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: List cargo version
        run: cargo --version
      - name: Install taplo
        run: cargo install taplo-cli --locked
      - name: List taplo version
        run: taplo --version
      - name: Run taplo
        run: taplo format --check --diff
      - name: Taplo failure info
        if: failure()
        run: |
          echo 'TOML is not formatted correctly'
          echo 'Please run `taplo format`'
