name: CI

permissions:
  contents: read
  pull-requests: read

on:
  pull_request:
    types:
      # These are the default types
      - opened
      - synchronize
      - reopened
      # This additional type is added to trigger on the 'ready for review' label being added
      - labeled
  push:
    branches: [develop, main]
  workflow_dispatch: # manual launch

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-files:
    runs-on: self-hosted
    outputs:
      skip: ${{ steps.check-files.outputs.skip }}
    steps:
      - uses: actions/checkout@v4
      - uses: tj-actions/changed-files@c65cd883420fd2eb864698a825fc4162dd94482c #v44.5.7
        id: changed-files
        with:
          # We check if workflow files were changed because changes to those should never be skipped either
          files: |
            **/.github/workflows/*
            **/*.rs
            **/Cargo.lock
            **/*.scale
      - name: Check if proper files changed
        id: check-files
        run: |
          if [[ "${GITHUB_EVENT_NAME}" == "workflow_dispatch" ]]; then
            echo "Triggered by workflow dispatch, not skipping."
            echo "skip=false" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          # If it is one of these branches, always run completely
          if [[ "${GITHUB_REF_NAME}" == "develop" || "${GITHUB_REF_NAME}" == "main" ]]; then
            echo "On develop or main branch."
            echo "skip=false" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          if [[ "${{ steps.changed-files.outputs.any_changed }}" == "false" ]]; then
            echo "No files changed. Skipping CI."
            echo "skip=true" >> "$GITHUB_OUTPUT"
          else
            echo "Some files changed. Running CI."
            echo "skip=false" >> "$GITHUB_OUTPUT"
          fi

  docs:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: "0.4.40"
      - name: Build the book
        run: mdbook build docs

  toml:
    if: ${{ needs.check-files.outputs.skip == 'false' && (contains(github.event.pull_request.labels.*.name, 'ready for review') || (github.ref_name == 'develop') || (github.ref_name == 'master')) }}
    runs-on: self-hosted
    needs: check-files
    steps:
      - uses: actions/checkout@v4
      - name: List versions
        run: |
          cargo --version
          taplo --version
      - name: Run taplo
        run: |
          taplo lint
          taplo fmt --check

  format:
    runs-on: self-hosted
    needs: toml
    steps:
      - uses: actions/checkout@v4
      - name: List version
        run: |
          cargo +nightly --version
          cargo +nightly fmt --version
      - name: Cargo format
        run: cargo +nightly fmt --all -- --check

  clippy_build_and_test:
    runs-on: self-hosted
    needs:
      - format
    env:
      RUSTFLAGS: -D warnings
      CARGO_LOG: cargo::core::compiler::fingerprint=info

    steps:
      - uses: actions/checkout@v4
      - name: List version
        run: |
          rustup show
          cargo --version
          cargo clippy --version
      # - uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0
      #   with:
      #     # Without breaks this self-hosted runners: https://github.com/Swatinem/rust-cache/issues/16
      #     cache-bin: false
      #     # cache-directories: "~/.cargo/registry/src/**/librocksdb-sys-*"
      - run: ln -s /home/ci/.global-target $PWD/target
      - name: Build in dev mode
        run: cargo build --profile ci --locked
      - name: Cargo clippy
        run: cargo clippy --profile ci --locked --no-deps

  check_tests:
    runs-on: self-hosted
    needs:
      - format
    env:
      RUSTFLAGS: -D warnings
      CARGO_LOG: cargo::core::compiler::fingerprint=info
    steps:
      - uses: actions/checkout@v4
      - name: List version
        run: |
          rustup show
          cargo --version
          cargo clippy --version
      # - uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0
      #   with:
      #     # Without breaks this self-hosted runners: https://github.com/Swatinem/rust-cache/issues/16
      #     cache-bin: false
      #     # cache-directories: "~/.cargo/registry/src/**/librocksdb-sys-*"
      - run: ln -s /home/ci/.global-target $PWD/target
      - name: Run tests
        run: cargo t --profile ci --locked --workspace --exclude maat
      - name: Check tests
        run: cargo clippy --profile ci --locked --no-deps

  check-benchmarks:
    runs-on: self-hosted
    outputs:
      skip: ${{ steps.check-benchmarks.outputs.skip }}
    steps:
      - uses: actions/checkout@v4
      - uses: tj-actions/changed-files@c65cd883420fd2eb864698a825fc4162dd94482c #v44.5.7
        id: changed-files
        with:
          files: |
            **/pallets/**/*.rs
            **/primitives/**/*.rs
            **/runtime/**/*.rs
            **/test-fixtures/**/*.rs
            **/Cargo.lock
            **/*.scale
      - name: Check if proper files changed
        id: check-benchmarks
        run: |
          if [[ "${{ steps.changed-files.outputs.any_changed }}" == "false" ]]; then
            echo "No files changed. Skipping CI."
            echo "skip=true" >> "$GITHUB_OUTPUT"
          else
            echo "Some files changed. Running CI."
            echo "skip=false" >> "$GITHUB_OUTPUT"
          fi

  # This is easier to configure in the GitHub settings
  benchmarks:
    runs-on: self-hosted
    needs:
      - check-benchmarks
      - format
    env:
      RUSTFLAGS: -D warnings
      CARGO_LOG: cargo::core::compiler::fingerprint=info

    if: ${{ needs.check-benchmarks.outputs.skip == 'false' }}

    steps:
      - uses: actions/checkout@v4

      # - uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0
      #   with:
      #     # Without breaks this self-hosted runners: https://github.com/Swatinem/rust-cache/issues/16
      #     cache-bin: false
      #     # cache-directories: "~/.cargo/registry/src/**/librocksdb-sys-*"

      - run: ln -s /home/ci/.global-target $PWD/target
      - name: Run test benchmarks
        run: |
          cargo test --profile ci --locked \
          -p pallet-storage-provider \
          -p pallet-proofs \
          -p pallet-randomness \
          --features runtime-benchmarks -- benchmark --nocapture

      - name: Run node benchmarks
        run: |
          cargo b -r -p polka-storage-runtime -F testnet -F runtime-benchmarks
          nix develop -c \
            frame-omni-bencher v1 \
              benchmark pallet \
              --runtime target/release/wbuild/polka-storage-runtime/polka_storage_runtime.compact.compressed.wasm \
              --pallet "pallet_storage_provider,pallet_proofs,pallet_randomness" \
              --extrinsic "*" \
              --steps 5 \
              --repeat 1
