name: Release

on:
  push:
    tags:
      - "**"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_release:
    runs-on: self-hosted
    # checks that the ref type is tag and it starts with polka-storage-v
    # currently no check for semantic version and that type of shit
    if: |
      github.ref_type == 'tag' && startsWith(github.ref_name, 'polka-storage-v')
    steps:
      - name: Build in release mode
        run: RUSTFLAGS="-D warnings" cargo build --release --locked
      - name: Release binaries
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # set github token for rw rights on repo
        with:
          tag_name: ${{ github.ref_name }} # set the name of the release the tag
          files: |
            target/release/mater-cli
            target/release/polka-storage-node
            target/release/polka-storage-provider-client
            target/release/polka-storage-provider-server
            target/release/storagext-cli
